In [4]:
import pandas as pd
from matplotlib.pyplot import plot
from sklearn.metrics import mean_squared_error
import numpy as np

In [31]:
df= pd.read_csv("C:/Users/DELL/Downloads/50_Startups.csv")

In [32]:
df.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [33]:
X=df.iloc[:,:-1].values
y=df.iloc[:,4].values

In [34]:
from sklearn.preprocessing import LabelEncoder , OneHotEncoder

In [35]:
le=LabelEncoder()

In [36]:
X[:,3]=le.fit_transform(X[:,3])
X

array([[165349.2, 136897.8, 471784.1, 2],
       [162597.7, 151377.59, 443898.53, 0],
       [153441.51, 101145.55, 407934.54, 1],
       [144372.41, 118671.85, 383199.62, 2],
       [142107.34, 91391.77, 366168.42, 1],
       [131876.9, 99814.71, 362861.36, 2],
       [134615.46, 147198.87, 127716.82, 0],
       [130298.13, 145530.06, 323876.68, 1],
       [120542.52, 148718.95, 311613.29, 2],
       [123334.88, 108679.17, 304981.62, 0],
       [101913.08, 110594.11, 229160.95, 1],
       [100671.96, 91790.61, 249744.55, 0],
       [93863.75, 127320.38, 249839.44, 1],
       [91992.39, 135495.07, 252664.93, 0],
       [119943.24, 156547.42, 256512.92, 1],
       [114523.61, 122616.84, 261776.23, 2],
       [78013.11, 121597.55, 264346.06, 0],
       [94657.16, 145077.58, 282574.31, 2],
       [91749.16, 114175.79, 294919.57, 1],
       [86419.7, 153514.11, 0.0, 2],
       [76253.86, 113867.3, 298664.47, 0],
       [78389.47, 153773.43, 299737.29, 2],
       [73994.56, 122782.75, 30331

In [37]:
oe=OneHotEncoder()

In [38]:
X=oe.fit_transform(X).toarray()
X

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       ...,
       [1., 0., 0., ..., 1., 0., 0.],
       [0., 1., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 1., 0., 0.]])

In [39]:
from sklearn.model_selection import train_test_split

In [40]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [41]:
X_train.shape

(40, 150)

In [42]:
X_test.shape

(10, 150)

In [43]:
from sklearn.linear_model import LinearRegression

In [44]:
lr=LinearRegression()

In [45]:
lr.fit(X_train,y_train)

LinearRegression()

In [49]:
y_pred=lr.predict(X_test)
y_pred

array([110811.56119446, 105687.093943  , 110811.56119446, 110811.56119446,
       110811.56119446, 118460.99039051, 118460.99039051, 118460.99039051,
       110811.56119446, 110811.56119446])

In [50]:
y_test

array([103282.38, 144259.4 , 146121.95,  77798.83, 191050.39, 105008.31,
        81229.06,  97483.56, 110352.25, 166187.94])

In [53]:
from matplotlib.pyplot import plt
x=df.iloc[:,1]
y=df.iloc[:,4]
plt.plot(x,y,'rx')

ImportError: cannot import name 'plt' from 'matplotlib.pyplot' (D:\Application\Lib\site-packages\matplotlib\pyplot.py)